development:
  adapter: postgresql
  host: localhost
  database: march
  username: march
  # password:
  encoding: UTF8
  schema_order: public
  allow_concurrency: true # TODO: informed decision
  # pool: 50
  # wait_timeout: 600

production:
  adapter: postgresql
  host: localhost
  database: march
  username: march
  # password:
  encoding: UTF8
  schema_order: public
  allow_concurrency: true # TODO: informed decision
  # pool: 50
  # wait_timeout: 600

